[package]
name = "convex_wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
lzma-rs = "0.3.0" 
lz-str = "0.2.1"
base64 = "0.22.1" 
log = "0.4.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
js-sys = "0.3"

[lib]
crate-type = ["cdylib", "rlib"]